[package]
name = "sdkwork-database-sqlx"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Sqlx-based database connection pool implementation for SDKWork"


[lints]
workspace = true
[features]
default = ["postgres"]
postgres = ["sqlx/postgres"]
sqlite = ["sqlx/sqlite", "dep:libsqlite3-sys"]
any = ["sqlx/any"]

[dependencies]
sdkwork_database_config.workspace = true

# Async runtime
tokio = { workspace = true }

# Database
sqlx.workspace = true
libsqlite3-sys = { workspace = true, optional = true }

# Serialization
serde = { workspace = true }

# Error handling
thiserror = { workspace = true }

# Logging
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tempfile = { workspace = true }
serial_test = "3"
